name: Repository Update
on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  packages: write

jobs:
  check-tmodloader-version:
    name: Check tModLoader Version
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/check-version.yml

  build:
    name: Build
    needs: check-tmodloader-version
    uses: ./.github/workflows/build.yml
    with:
      SHOULD_UPDATE: ${{ needs.check-tmodloader-version.outputs.SHOULD_UPDATE }}
      REPO_VERSION: ${{needs.check-tmodloader-version.outputs.REPO_VERSION}}
      CURRENT_VERSION: ${{needs.check-tmodloader-version.outputs.CURRENT_VERSION}}

  tests:
    name: Tests
    needs:
      - check-tmodloader-version
      - build
    uses: ./.github/workflows/test.yml
    with:
      SHOULD_UPDATE: ${{ needs.check-tmodloader-version.outputs.SHOULD_UPDATE }}
      REPO_VERSION: ${{needs.check-tmodloader-version.outputs.REPO_VERSION}}
      CURRENT_VERSION: ${{needs.check-tmodloader-version.outputs.CURRENT_VERSION}}

  update-tmodloader-image:
    name: Update Docker Image in Docker Registry
    if: github.event.pull_request.merged == true
    needs:
      - check-tmodloader-version
      - tests
    uses: ./.github/workflows/update-tmodloader-image.yml
    secrets: inherit
    with:
      SHOULD_UPDATE: ${{ needs.check-tmodloader-version.outputs.SHOULD_UPDATE }}
      REPO_VERSION: ${{needs.check-tmodloader-version.outputs.REPO_VERSION}}
      CURRENT_VERSION: ${{needs.check-tmodloader-version.outputs.CURRENT_VERSION}}

  publish-control-images:
    name: Publish Control Images
    if: github.event.pull_request.merged == true
    needs: tests
    uses: ./.github/workflows/publish-control-images.yml
    secrets: inherit
